---
title: "R Notebook"
output: html_notebook
---


```{r,warning=FALSE}
library("tidyverse")
```

# surporting function
```{r}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}
data<-read.csv("F:/R Tutorials/Survey data combined.csv")
```

```{r}

glimpse(data)
```
```{r}
data<- as.tibble(data)
```
```{r}
dim(data)
```
```{r}
colnames(data)
```
```{r}
p1<- data %>% 
  mutate(NO= as.integer(NO)) %>% 
  ggplot(aes(NO,fill= as.factor(NO)))+
  geom_bar(width = 8)+
  theme(legend.position = "none")

p2<-data %>% 
  ggplot(aes(TEMPK))+
  geom_histogram(bins = 50, fill="red")+
  theme(legend.position = "none")

p3<-data %>% 
  ggplot(aes(DEPTH))+
  geom_histogram(bins = 50, fill="blue")+
  theme(legend.position = "none")


layout= matrix(c(1,1,2,3),2,2, byrow = TRUE)
multiplot(p1,p2,p3, layout = layout)


```

